-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 17:00:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrera` (
  `ID_carrera` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Resolucion` VARCHAR(45) NOT NULL,
  `Modalidad` VARCHAR(45) NOT NULL,
  `Duracion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_carrera`),
  UNIQUE INDEX `Resolucion_UNIQUE` (`Resolucion` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos` (
  `ID_Alum` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `DNI` INT NOT NULL,
  `Domicilio` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `Edad` INT NOT NULL,
  `Género` VARCHAR(45) NOT NULL,
  `id_carre_corresp` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`ID_Alum`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `id_carre_corresp_idx` (`id_carre_corresp` ASC) VISIBLE,
  CONSTRAINT `id_carre_corresp`
    FOREIGN KEY (`id_carre_corresp`)
    REFERENCES `mydb`.`carrera` (`ID_carrera`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_evaluación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_evaluación` (
  `ID_Tipo_evaluación` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tipo_evaluación`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `ID_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `DNI` INT NOT NULL,
  `Domicilio` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `Edad` INT NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Cuil` VARCHAR(45) NOT NULL,
  `id_carrerac` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`ID_Profesor`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `ID_Profesor_UNIQUE` (`ID_Profesor` ASC) VISIBLE,
  UNIQUE INDEX `Cuil_UNIQUE` (`Cuil` ASC) VISIBLE,
  INDEX `id_carrerac_idx` (`id_carrerac` ASC) VISIBLE,
  INDEX `anio_idx` (`anio` ASC, `id_carrerac` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materias` (
  `ID_materias` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `id_prof_corresp` INT NOT NULL,
  `anio` INT NOT NULL,
  `id_carre_corresp` INT NOT NULL,
  PRIMARY KEY (`ID_materias`),
  UNIQUE INDEX `ID_materias_UNIQUE` (`ID_materias` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  INDEX `id_prof_corresp_idx` (`id_prof_corresp` ASC) VISIBLE,
  INDEX `id_carre_corresp_idx` (`id_carre_corresp` ASC) VISIBLE,
  CONSTRAINT `id_prof_corresp`
    FOREIGN KEY (`id_prof_corresp`)
    REFERENCES `mydb`.`profesor` (`ID_Profesor`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluaciones` (
  `ID_evaluaciones` INT NOT NULL AUTO_INCREMENT,
  `id_alum` INT NOT NULL,
  `Id_materia` INT NOT NULL,
  `Curso` INT NOT NULL,
  `Evaluación_id` INT NOT NULL,
  `Calificación` INT NOT NULL,
  PRIMARY KEY (`ID_evaluaciones`),
  UNIQUE INDEX `ID_evaluaciones_UNIQUE` (`ID_evaluaciones` ASC) VISIBLE,
  INDEX `Id_materia_idx` (`Id_materia` ASC) VISIBLE,
  INDEX `Id_alum_idx` (`id_alum` ASC) VISIBLE,
  INDEX `Evaluación_id_idx` (`Evaluación_id` ASC) VISIBLE,
  CONSTRAINT `Evaluación_id`
    FOREIGN KEY (`Evaluación_id`)
    REFERENCES `mydb`.`tipo_evaluación` (`ID_Tipo_evaluación`),
  CONSTRAINT `Id_alum`
    FOREIGN KEY (`id_alum`)
    REFERENCES `mydb`.`alumnos` (`ID_Alum`),
  CONSTRAINT `Id_materia`
    FOREIGN KEY (`Id_materia`)
    REFERENCES `mydb`.`materias` (`ID_materias`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`libreta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libreta` (
  `Materia_id` INT NOT NULL,
  `Evaluacion_id` INT NOT NULL,
  `Calificacion` INT NOT NULL,
  `alum_id` INT NOT NULL,
  INDEX `FK_Evaluación_id_idx` (`Evaluacion_id` ASC) VISIBLE,
  INDEX `FK_alum_id_idx` (`alum_id` ASC) VISIBLE,
  CONSTRAINT `FK_alum_id`
    FOREIGN KEY (`alum_id`)
    REFERENCES `mydb`.`alumnos` (`ID_Alum`),
  CONSTRAINT `FK_Evaluación_id`
    FOREIGN KEY (`Evaluacion_id`)
    REFERENCES `mydb`.`tipo_evaluación` (`ID_Tipo_evaluación`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
